		 
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections.ObjectModel;

namespace CodeGen.State
{
	public class PersonState 
    {
		public Int32 Id { get; set; } 
		public String Name { get; set; } 
		public Int32 AddressId { get; set; } 
		public String AddressStreet { get; set; } 
		public Int32 AddressZipCode { get; set; } 
	}
}
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
