		 
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections.ObjectModel;

namespace ModuleA.Data
{
	public class SettingsState 
    {
		public String Name { get; set; } 
		public String Value { get; set; } 
		public Guid Id { get; set; } 
	}
}
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
